config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'static_pages#index'
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fishburne.rb
class Fishburne < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :members
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
end

app/controllers/fishburne_controller.rb
class FishburneController < ApplicationController
	def index
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  
  def index
    @members = Member.all
  end

  def new
    @member = Member.new
  end

  def create
    @member = current_user.members.create(member_params)
    if @member.valid?
    redirect_to members_path
     else
    render :new, status: :unprocessable_entity
  end
end

  def show
     @members = Member.find(params[:id])
  end

private
  
  def member_params
    params.require(:member).permit(:name, :rank, :year)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/fishburne_helper.rb
module FishburneHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/fishburne/index.html.erb
<body>
	<p>hello</p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FMSCG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'FMS COLOR GUARD', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= link_to 'Members', members_path, class: 'nav-link' %>
      </li>
      <li>
        <%= link_to 'New Members', new_member_path, class: 'nav-link' %>
      </li>
      <div class='float-right'>
      <li>
        <ul class="navbar-nav">
      <% if user_signed_in? %>        
        <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
      <li class ="nav-item">
         <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
      </li>
        <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    </li>
      <% end %>
    </ul>
  </div>
</nav>
 


  <% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

   
  </head>
  <body>
  <script>

    function initMap() {
      var myLatLng = {lat: 38.068, lng: -78.891};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 4,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDIMnz2vTi0j_AcrmAcVvC4NWzlKoNmkGI&callback=initMap">
  </script>
    
    <%= yield %>
  </body>
</html>

  

app/views/members/index.html.erb
<div class="members-box">
<% @members.each do |member| %>
  <div class="members-box col-10 offset-1">
  <h1><%= member.name %></h1><br />
  <i><%= member.rank %></i><br />
  <h4><%= member.year %></h4>
</div>
<% end %>
</div>

app/views/members/new.html.erb
<div class="members-box">
<h1>Enter The Members Details</h1>
<%= simple_form_for @member do |f| %>
  <%= f.input :name %><br />
  <%= f.input :rank %><br />
  <%= f.input :year %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/members/show.html.erb
<div class="members-box">
<% @members.each do |member| %>
  <div class="members-box col-8 offset-2">
  <h1><%= member.name %></h1><br />
  <i><%= member.rank %></i><br />
  <h4><%= member.year %></h4>
</div>
<% end %>

app/views/static_pages/index.html.erb
<title>FMS-CG</title>

<head>
  <style>
  @import url('https://fonts.googleapis.com/css?family=Oswald|Playfair+Display|Roboto&display=swap');
  </style>

</head>

<body>
   <h1>Fishburne Military School Color Guard</h1>
<div class="img">
  <%= image_tag("cg.1.jpg") %>
</div>
<div class="intro col-10 offset-1">
  <p>
    <h3>The Fishburne military school color guard is an elite drill and ceremony unit. Which during my years on the team we performed for the orioles, nationals, Newday USA, and the presidents chapter dinner for AUSA. The colorguard has had the destinct honor of presenting the colors for AUSA's president during their annual dinner eight years now.</h3>
  </p>
</div>
<div class="map-wrapper">
   <div id="map"></div>
</div>
</body>